# Configuration: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository
blank_issues_enabled: false
contact_links:
  - name: ğŸ˜ Contribution Guide
    url: https://github.com/davnn/uv-pack/blob/main/.github/CONTRIBUTING.md
    about: Please read through before making a contribution.
